services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-api
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb+srv://admin:admin123@cluster0.5pjzvgg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - MONGO_DATABASE=ecommerce
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - ORDERS_QUEUE=orders
      - GIN_MODE=release
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - ecommerce-network
    restart: unless-stopped

networks:
  ecommerce-network:
    driver: bridge
